### PR TITLE
CI/CD Proposal

### PR DESCRIPTION
**Pull request by juanitorduz**
Hey @ColtAllen! Here is a first proposal of the CI/CD pipeline. I am not an expert ni the topic but at least this should be a good start for discussion. At the moment I am checking for code style  (lint) and tests. They are failing but at least the errors are the same I get locally ;) So feel free to look int the error logs. 
- With respect to the linit, which code style and config are you using. In this initial PR i added black, isort and flake8. We can of course change this.
- I also had to add `liifetimes` as a dev dependency because otherwise the test fail.

### CODE REVIEW

**Comment by ColtAllen** [comment]
Thanks for the PR, @juanitorduz!

> With respect to the linit, which code style and config are you using. In this initial PR i added black, isort and flake8. We can of course change this.

Code style is unspecified at this time.

> I also had to add liifetimes as a dev dependency because otherwise the test fail.

Interesting; which tests were failing?

**Comment by juanitorduz** [comment]
My bad! Tests are fine! It was a mistake on my side, see https://github.com/ColtAllen/btyd/pull/38/commits/681cff50dcc9ceec036f98c20c2c057044b44189

**Comment by ColtAllen** [comment]
Was Python 3.8 failing during testing? I noticed PyMC 4.1 removed support for 3.7.

**Comment by juanitorduz** [comment]
> Was Python 3.8 failing during testing? I noticed PyMC 4.1 removed support for 3.7.

Is not working as it is a current requirement of the `btyd` package, see https://github.com/ColtAllen/btyd/blob/main/pyproject.toml#L10

**Comment by juanitorduz** [comment]
As the code style is not set now I added a placeholder in the ci/cd checks (see https://github.com/ColtAllen/btyd/pull/38/commits/8b8592ca4dce7ec340066be469e0a8be6be85f22) . 

If we decide to merge this PR which runs the test (by setting the env via poetry), could work on adding the style suggested here as well (which is pretty standard)

**Comment by ColtAllen** [comment]
> > Was Python 3.8 failing during testing? I noticed PyMC 4.1 removed support for 3.7.
> 
> It is not working as it is a current requirement of the `btyd` package, see https://github.com/ColtAllen/btyd/blob/main/pyproject.toml#L10

My bad 😲 I've been testing `btyd` in 3.9.5. That line can be changed to "^3.8" in the .toml file. 

After the `fitters.py` module is deprecated in beta, The only dependency `btyd` will have is `pymc` and the transitive dependencies thereof, which is minimal enough to justify using Poetry for package management (I would never use Poetry for packaging ML pipelines in my day job.)

 This means the minimum python requirements of `btyd` will match that of `pymc`, and since the latest version of `pymc` has dropped support for 3.7, it's best to restrict `btyd` to 3.8 and above.

**Comment by juanitorduz** [comment]
Is all green! Yay! I had to remove for now the python 3.10 tests as `scipy` as giving some weird errors I don't wanna go ini this first iteration if this is ok with you. I think the code style is a bit higher priority IMO. :)

**Comment by ColtAllen** [comment]
> Is all green! Yay! I had to remove for now the python 3.10 tests as `scipy` as giving some weird errors I don't wanna go ini this first iteration if this is ok with you. I think the code style is a bit higher priority IMO. :)

Agreed; I'll go ahead and merge this. CI/CD just in time for some last minute code tweaks & additions before I publish the beta release. Thanks again!

**Pull request merged**
